In [77]:
from tensorflow.keras.preprocessing.text import one_hot

In [78]:
### sentences
sent=[  'the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good',]

In [79]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [80]:
## Define the vocabulary size
voc_size=10000

In [81]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [82]:
### One Hot Representation
one_hot_repr=[one_hot(words,voc_size)for words in sent]
one_hot_repr

[[5426, 8825, 9450, 370],
 [5426, 8825, 9450, 1316],
 [5426, 2296, 9450, 201],
 [1714, 738, 9624, 3192, 5798],
 [1714, 738, 9624, 3192, 6060],
 [9966, 5426, 7711, 9450, 8562],
 [4049, 9692, 3049, 3192]]

In [83]:
## word Embedding Representation

from tensorflow.keras.layers import Embedding
#from tensorflow.keras.processing.sequence import pad_sequences
from tensorflow.keras.utils import pad_sequences
from tensorflow.keras.models import Sequential

In [84]:
import numpy as np

In [85]:
sent_length=8
embedded_docs=pad_sequences(one_hot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[   0    0    0    0 5426 8825 9450  370]
 [   0    0    0    0 5426 8825 9450 1316]
 [   0    0    0    0 5426 2296 9450  201]
 [   0    0    0 1714  738 9624 3192 5798]
 [   0    0    0 1714  738 9624 3192 6060]
 [   0    0    0 9966 5426 7711 9450 8562]
 [   0    0    0    0 4049 9692 3049 3192]]


In [86]:
## feature representation
dim=10

In [87]:
model=Sequential()
model.add(Embedding(voc_size,dim,input_length=sent_length))
model.compile('adam','mse')

In [88]:
model.summary()

Model: "sequential_8"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_8 (Embedding)         │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [89]:
model.predict(embedded_docs)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 86ms/step


array([[[ 0.0472951 ,  0.0233779 ,  0.00794063,  0.04214969,
          0.03429636,  0.04192139, -0.03976528,  0.03448376,
         -0.00571596, -0.02503462],
        [ 0.0472951 ,  0.0233779 ,  0.00794063,  0.04214969,
          0.03429636,  0.04192139, -0.03976528,  0.03448376,
         -0.00571596, -0.02503462],
        [ 0.0472951 ,  0.0233779 ,  0.00794063,  0.04214969,
          0.03429636,  0.04192139, -0.03976528,  0.03448376,
         -0.00571596, -0.02503462],
        [ 0.0472951 ,  0.0233779 ,  0.00794063,  0.04214969,
          0.03429636,  0.04192139, -0.03976528,  0.03448376,
         -0.00571596, -0.02503462],
        [ 0.04545101,  0.03344939, -0.03096868, -0.01726103,
         -0.00455521,  0.04756233, -0.02296372,  0.00344499,
          0.03826498, -0.02706074],
        [-0.02139872,  0.00352744,  0.01629216,  0.03478572,
         -0.01718819,  0.0453544 , -0.02972551,  0.04750198,
          0.03204446,  0.02774673],
        [ 0.0367124 ,  0.03826335, -0.03724508,  0.0

In [90]:
embedded_docs[0]

array([   0,    0,    0,    0, 5426, 8825, 9450,  370], dtype=int32)

In [91]:
#model.predict(embedded_docs[0])


# # Step 1: Examine your data
# print("=== INPUT ANALYSIS ===")
# print(f"embedded_docs type: {type(embedded_docs)}")
# print(f"embedded_docs length: {len(embedded_docs)}")
# print(f"First element type: {type(embedded_docs[0])}")
# print(f"First element shape: {getattr(embedded_docs[0], 'shape', 'No shape attribute')}")

# # Step 2: Examine your model
# print("\n=== MODEL ANALYSIS ===")
# print(f"Model input shape: {model.input_shape}")
# print(f"Model summary:")
# model.summary()

# Step 3: Prepare input correctly
try:
    # Convert to numpy array if needed
    if not isinstance(embedded_docs[0], (np.ndarray, tf.Tensor)):
        input_data = np.array(embedded_docs[0])
    else:
        input_data = embedded_docs[0]
    
    # Add batch dimension if needed
    if len(input_data.shape) == len(model.input_shape) - 1:
        input_data = np.expand_dims(input_data, axis=0)
    
    # Make prediction
    prediction = model.predict(input_data)
    print(f"Prediction successful: {prediction}")
    
except Exception as e:
    print(f"Error: {e}")
    print("Try reshaping your input data to match model expectations")

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 51ms/step
Prediction successful: [[[ 0.0472951   0.0233779   0.00794063  0.04214969  0.03429636
    0.04192139 -0.03976528  0.03448376 -0.00571596 -0.02503462]
  [ 0.0472951   0.0233779   0.00794063  0.04214969  0.03429636
    0.04192139 -0.03976528  0.03448376 -0.00571596 -0.02503462]
  [ 0.0472951   0.0233779   0.00794063  0.04214969  0.03429636
    0.04192139 -0.03976528  0.03448376 -0.00571596 -0.02503462]
  [ 0.0472951   0.0233779   0.00794063  0.04214969  0.03429636
    0.04192139 -0.03976528  0.03448376 -0.00571596 -0.02503462]
  [ 0.04545101  0.03344939 -0.03096868 -0.01726103 -0.00455521
    0.04756233 -0.02296372  0.00344499  0.03826498 -0.02706074]
  [-0.02139872  0.00352744  0.01629216  0.03478572 -0.01718819
    0.0453544  -0.02972551  0.04750198  0.03204446  0.02774673]
  [ 0.0367124   0.03826335 -0.03724508  0.04532545  0.01168754
   -0.03255065 -0.04461084  0.02210673 -0.01321846 -0.01455507]
  [-0.04609928  0.00600457 -0.04359458  0.00439482